### ISSUE TITLE
custom step groups

### ISSUE THREAD

**Issue by yaythomas** [pypyr/pypyr-cli#126]
steps are defined in the pipeline yaml by being a list in step-groups. pypyr currently has these built-in step-groups:
- steps
- on_success
- on_failure

rewire the core so that we can introduce custom step-groups, i.e user specified step groups. this will (finally!) mean that _on_success_ makes a bit more sense - a pipeline can jump between step-groups, and _on_success_ runs when the last step_group finishes. _on_failure_ remains the general "catch all" exception handler. It's maybe a thought to allow a custom err handler to over-ride the general _on_failure_ catch-all?

this will help from an API perspective with a feature request from @Reskov to resume/re-run a pipeline with more flexibility. 

this core change will ultimately allow the following:
1. specify `--groups group1 group2 group3` as a pypyr cmd switch, meaning user can specify which groups to run. If not specified, defaults to "steps", per usual.
2. add a step _pypyr.steps.jump_ that takes input
    ```
    jump: [group1,group2,group3]
    ```
    jump is effectively a GOTO. 
3. add a step _pypyr.steps.grouprun_ - this is an inline execute of another group. you're not jumping to another group, you are executing the steps of the group as a function/method, meaning the pipeline will keep going with the next step after this is done rather than transfer control to the new groups like _jump_.

    input also a list of group-names, as with _jump_.
   possible names:
   source, exec, dostepgroup
4. allow _pypyr.steps.pype_ optionally to specify which groups to run in a child pipeline

**Comment by Reskov** [comment]
@345thomas excellent! any plans to jump to a specific group step? something like
`jump: [group group1:2 group2:3]`

or even similar to python slice
`jump: [group:start:stop group2]`

**Comment by 345thomas** [comment]
In a perfect world, yes, the python slice style syntax would be great for a to and from step! 

there're couple of challenges here that still need thinking through, 
* what if group name is "mygroup:checkthatarbitrarycolon"?
* loops? just jumping to step, or also also jump into loop iteration?: `[group]:[step-start]:[step-stop]`, same sort of syntax `[group]:[step-start]:[whilecounter]:[foritem]:[step-stop]:[whilecounter]:[foritem]` gets a bit silly
* unless a pipeline author really eally knows what they're doing, this func will make it very easy to make mistakes or worse, not be useful. . . it's going to be up to the author to make the pipeline take a context input that A) runs normally and B) supports loading in a partial context on a jump-to-step style run C) make sure that the context has everything it needs by the time it gets to step x (i.e maybe steps x-1 and x-2 set/mutated things in context that step x needs). None of this is impossible, and for the simplest of cases it's not _necessarily_ a worry (e.g simply running a couple of steps that don't particularly need any context other than what they set up/hard-code themselves), but it'll be easy for this not to be easy.

Jump to specific step is probably enough of a topic/change that I'm going to ticket that separately. Let's focus on custom groups first, and when we've done those we can see better where the edges are for doing step-jumps. . .
