### ISSUE TITLE
Pypyr context get_formatted_iterable not support of the read-only mapping

### ISSUE THREAD

**Issue by Reskov** [pypyr/pypyr-cli#181]
The assignment operation is not supported by the `typing.Mapping` class. 

When I try to use `get_formatted_iterable` on the immutable type like `immutables.Map`, `multidict.MultiDictProxy`  or custom typing.Mapping, the `context.get_formatted_iterable` https://github.com/pypyr/pypyr-cli/blob/841be7e6859f3dcb430d8056d70c604a4fd581d6/pypyr/context.py#L354-L355  raises a `TypeError`

Example:
```python
class ReadOnlyMapping(typing.Mapping):
    def __init__(self, *args, **kwargs):
        self._data = dict(*args, **kwargs)

    def __getitem__(self, key):
        return self._data[key]

    def __len__(self):
        return len(self._data)

    def __iter__(self):
        return iter(self._data)

input_obj = {'key': '{ctx}'}

context = Context({'ctx': ReadOnlyMapping({'arb': 1})})

output = context.get_formatted_iterable(input_obj)
```

produce

```
TypeError: 'ReadOnlyMapping' object does not support item assignment
```

**Comment by yaythomas** [comment]
Thanks @Reskov, looking good!

ci is failing. . . looks like flake8 has recently introduced a new rule that's causing failures elsewhere (i.e nothing to do with your change). I'll push up a fix in a little bit, looking at it right now.
