### ISSUE TITLE
Execute pypyr from python code

### ISSUE THREAD

**Issue by Reskov** [pypyr/pypyr-cli#80]
Hello,

First of all let me thank you, for a nice project. 

I plan to use pypyr not as cli, but as remote command executor, using template dynamically loaded from config service like zookeeper.

So my questions is:
1) btw is this totally a good idea to use pypyr not as cli, but as single runner service, or I am going a wrong way?

2) if so, is any plan to support for step restrictions or sandboxing, due to I do not want to allow my user to run custom shell script?

3) Is any plan to get asyncio support? I want to run the same script multiple times separately for different users, and my steps will have a lot of i/o operations.

Thanks

**Comment by 345thomas** [comment]
> I plan to use pypyr not as cli, but as remote command executor, using template dynamically loaded from config service like zookeeper.

If by template you mean a you want to load yaml or json config into the pypyr context, [fetchjson](https://github.com/pypyr/pypyr-cli#pypyr-steps-fetchjson) and [fetchyaml](https://github.com/pypyr/pypyr-cli#pypyr-steps-fetchyaml) are examples of ready-made steps that do so from disk. In the pypyraws, there are steps that load [json](https://github.com/pypyr/pypyr-aws#pypyraws-steps-s3fetchjson) or [yaml](https://github.com/pypyr/pypyr-aws#pypyraws-steps-s3fetchyaml) config dynamically from aws s3.
Obviously neither of these are zookeeper, but hopefully the examples help 😄 

If by template you mean you want to get the pipeline yaml itself from Zookeeper, at easiest you can zookeeper `get` and dump the pipeline yaml to disk _./pipelines/mypipelinedumpedfromzookeeper.yaml_ and then run `pypyr mypipelinedumpedfromzookeeper`. 

> 1. btw is this totally a good idea to use pypyr not as cli, but as single runner service, or I am going a wrong way?

You can absolutely use pypyr as a python api library, you don't have to use the cli. In fact, all the cli functions are encapsulated in `./pypyr/cli.py`, the rest of the call-chain is just good ol' python, doesn't matter where you call it from. 

The most obvious, or sensible, entrypoint, would be _./pypyr/pipelinerunner.py_, either `main` or `run_pipeline`. There are some end-to-end tests that demonstrate exactly this: check _/tests/unit/pypyr/pipelinerunner_test.py_ for examples to get you started on `main` or `run_pipeline` - check the smoke test at the very bottom. 

> 2. if so, is any plan to support for step restrictions or sandboxing, due to I do not want to allow my user to run custom shell script?

If you allow your users to create their own pipelines, or to influence the content of risky steps, then yes, you're absolutely right, they will have an unholy amount of opportunity to do damage. Particularly risky steps are: 
* pypyr.steps.shell
* pypyr.steps.safeshell
* pypyr.steps.py
* pypyr.steps.tar
* pypyr.steps.env - set and unset

But there are other steps that could also do damage if you're not trusting the user. . . any of the _fileformat_ or _filereplace_ steps could be used for mischief if someone wanted to overwrite or mess with important files. I guess what I'm trying to say is that pypyr is a power tool, and there are so many steps that can do damage, I don't know where a sandbox mode should be drawing the boundary? Happy to hear you suggestions on the topic?

So philosophically, the way the security boundary is drawn is by restricting which pipelines are available to run - the pipeline yaml itself is the thing that is vetted/source-controlled/PRd to make sure someone isn't doing `rm -rf /` or similar.

Even if you're loading context dynamically from somewhere that users can influence (like zookeeper), the context will only be operated on by whatever steps exist in the pipeline. So the question is whether users get to define pipelines that are unreviewed/unchecked.

Sandboxing this is an interesting question: if the user has access to the cli they'd be able to over-ride that, but if you are controlling the execution environment and you only allow them to specify a pipeline-name, effectively, you could also prevent them from running the unsafe steps listed above. There is no such functionality at present. 

> 3. Is any plan to get asyncio support? I want to run the same script multiple times separately for different users, and my steps will have a lot of i/o operations.

I do have a task for exactly this #57. I have to admit, though, I go through phases of wondering whether it's a sensible idea or not. There are two ways of going about running in parallel: 
* run the cli (or `./pipelinerunner/main()` if you're using it as an api) in parallel. 
* create a step decorator that only iterates over a single step in parallel. 

Option 1 you can obviously already do today: quite simply invoke the cli multiple times, or let your bootstrap code that call main() call it multiple times, and author the pipeline yaml in a way that makes sense for such execution.

If you are planning on using pypyr as an api, this gets even easier - you're already in control of exactly how you want to invoke `./pipelinerunner/main()`, so you can asyncio it right there and then.

As a last, more generalized comment, I actually use pypyr as a remote command executor myself all the time, but I go about it in a different way: I use the [pypyr docker image](https://github.com/pypyr/pypyr-docker-img) to run pypyr in any given environment that can run a docker image - something like aws ecs or kubernetes. I then use the `fetchjson` or `fetchyaml` steps to load dynamic config from either disk or from s3 - as I described further up. In the case of aws ecs you can kick off the execution via a lambda function so you effectively have a rest end-point for "start", or any given bit of workflow that starts the container, and ditto for kubernetes. 
This is also an easy way of achieving the parallel running, quite simply by kicking off the docker run multiple times. 

Hopefully I answered your questions and hopefully I helped! I'd love to hear more about what you're planning, it sound interesting!

**Comment by Reskov** [comment]
Thank you very much for a detailed and quick response.

# Long story:

I’m working on a backend web-service that will operate with several consumers (each consumer have own set of users, and business use-cases),

For example, current flow for end-point list of items, looks like this

- check authorization
- check user permission
- load user context
- list items for user
- return the result or error message

any consumer should be able to redefine any of these steps, for example authorization (consumer may customize its own)
what I want to provide, with the help of your library, of course, is the capability to redefine logic (partially only some of the steps, not all, using admin interface, and without service reload)

# Answers
1) thanks for the good recommendation, I have tried **run_pipeline** method, everything seems work pretty well.

Extra question here, is any opportunity to cache the pipeline because I have a very poor performance loading yaml each time

Seems it may be optimized in my case with something like this
```python
    if pipeline_name not in _cache:
        _cache[pipeline_name]=pypyr.pipelinerunner.get_pipeline_definition(
            pipeline_name=pipeline_name,
            working_dir=working_dir,
        )

    pypyr.pipelinerunner.run_pipeline(
        pipeline_name=pipeline_name,
        pipeline_context_input="",
        pipeline_definition=_cache[pipeline_name],
        working_dir=working_dir,
        context=context,
        parse_input=False
    )
```

argument **pipeline_definition** is what I'm suggesting
And here is result, for my simple app with one step:
 _Requests/sec: 1541.72_ with cache, 
 _Requests/sec: 200.14_ without cache

2) I'll think about it, probably the easiest way is to make a separate isolated environment through the docker, also I am thinking about something like https://github.com/zopefoundation/RestrictedPython or pypy while it will be more complicated, I will return to this question later while I need to check other things first. 
Seems it is not a big problem.

3) I use REST API web service as a backend, based on **aiohttp**, and as I said before I tried to implement the same endpoints to have a customizable behavior for different consumers,
therefore, it is so important for me to use **asyncio** coroutines to not to block the event cycle of the entire application while the step is waiting for the pypyr.pipeline to be completed (the Threads will not be enough, in my case I'm running all steps sequentially)
So in case if in time of execution another user comes, he will wait for the synchronous code for the first one to complete for other one, that drastically impact on the performance)

may we support coroutines as steps, probably, it should not be a lot of refactoring to support such implementation?
```
async def run_pipeline(..)
async def run_step_group(...)
async def run_pipeline_steps(..)
```
and so on
I may prepare PR if you agree with point 1 and 3

**Comment by 345thomas** [comment]
Thanks Reskov! That's an interesting use-case you have there!

Sorry I've taken a bit longer to reply to this one, I was thinking carefully through your proposals.

1. 
Yes, the yaml involves disk io AND parsing, so it's for sure slow. While the simple memoization you're proposing will work, it will also introduce challenges: an infinitely growing cache, no way to refresh the cache without killing the process, potentially very high memory consumption.

I'd rather introduce refactor to move out get_pipeline_definition out of run_pipeline, by adding a new func like:
```
def load_and_run_pipeline(pipeline_name,
                          pipeline_context_input=None,
                          working_dir=None,
                          context=None,
                          parse_input=True):

       # pipeline loading deliberately outside of try catch. The try catch will
       # try to run a failure-handler from the pipeline, but if the pipeline
       # doesn't exist there is no failure handler that can possibly run so this
       # is very much a fatal stop error.
       pipeline_definition = get_pipeline_definition(pipeline_name=pipeline_name,
                                                     working_dir=working_dir)

       run_pipeline(pipeline=pipeline_definition,
                    pipeline_context_input=pipeline_context_input,
                    working_dir=working_dir)
```

main() can then call this function. API consumers like yourself can then pick and choose how to load that pipeline, or how to cache it, but more importantly, you get to control as api consumer when/how to refresh your cache.


3.
Again, while the change you propose would certainly solve your immediate problem. . . there are a couple of deeper issues here. 

Firstly, pypyr is not at all coded to be fast. It's not even on the map, in all honesty. It started of life as a devops/cli helper, where optimizing for speed was never on the objective list. So nevermind asyncing the code, so much of it is going to be slow, that I think merely making co-routines out of all the functions aren't necessarily going to help matters as much as you'd think - it wouldn't address the underlying performance/low-footprint requirements of running within the context of a web-server process.

If anything, future additions to pypyr might well make the pipeline interpretation _more_ complex, not less, so even there, philosophically, being fast and light are not fundamental design constraints going forward, and I'm trying to careful that you don't shoot yourself in the foot with making a big architectural decision at the beginning of the project that might result in inefficiencies that are difficult to fix down the line.

In keeping with designing for scale strategies, you might want to design your web-service to work asynchronously. i.e 
-> web request
-> web-service puts payload on queue (something like kafka, say) 
-> listeners process workload from queue and runs longer running processes, like pypyr, via api 
-> on long running process completion, notify web-server for async callback

You'd massively reduce contention, memory, cpu and disk io on your web-servers this way.

Sorry if that's not quite the response you were looking for, and I don't mean to nitpick over your architecture, but I'm trying to consider the wider audience in addition to your use case, and trying to make sure that we're not introducing more problems than we solve 😄

**Comment by Reskov** [comment]
1. Nice, that would be great for me, is any plan to get this working soon, should I prepare PR for that, to get this feature quicker?
3. I already thought about Apache OpenWhisk or AWS Step function, totally agree with your point of view, and I understand that library has different purpose, I'm just planning to use own custom steps, so future releases probably shouldn't affects me so much, thanks again for guidance and help, I'll take a risk, and I'll try to keep my feet undamaged :) 

Just add another point about futures, it would be easy to create async/parallel step (No need for threads, *asyncio* all ready have it inside the box).

**Comment by 345thomas** [comment]
1. if you want to PR that, I would mightily appreciate it! 

Be warned that I've a suspicion that as relatively simple as the functional refactor is, the unit/integration tests are going to have some knock-on impact - `pipelinerunner_test` uses a whole lot of mocks to intercept various parts of the process. 

Check https://github.com/pypyr/pypyr-cli/blob/master/CONTRIBUTING.rst to get you started - you can run the whole CI testing and quality validation process locally to save yourself trouble and time. So if you still have the stomach for it, go for it! 😀 

2. Yes, #57 the plan was indeed asyncio for the async/parallel load style step. . . me imprecisely using the word "threads" is probably betraying my age and background a bit. . .

**Comment by Reskov** [comment]
That was very helpful, thanks again

**Comment by 345thomas** [comment]
my pleasure!
